apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-db
  template:
    metadata:
      labels:
        app: main-db
    spec:
      containers:
        - name: main-db
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: main-db-srv
spec:
  selector:
    app: main-db
  ports:
    - name: main-app-db
      protocol: TCP
      port: 5432
      targetPort: 5432
