name: deploy-manifests
on:
  push:
    branches:
      - master
    path:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #check out all of our code inside of our repo
      - uses: actions/checkout@v2
  

      # Install doctl
      name: install doctl into our running github container
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # Get the cluster config and save it inside the container
      # So this will give us a pre initialized copy of all the context information we need, should also make that the active context on doctl as well
      name: Get the cluster config file
      - run: doctl kubernetes cluster kubeconfig save lafamilia

      name: update deployment 
      # We tell the deployment to update itself and use the latest image that  we just pushed to Docker hub

      # The command that we going to use to restart a deployment is 
      - run: kubectl apply -f infra/k8s
